### ISSUE TITLE
Can't deploy with latest dokku and buildstep

### ISSUE THREAD

**Issue by amaltson** [progrium/buildpack-nginx#1]
I upgraded to the latest Dokku 0.2.0 and the latest buildstep last night. Now I'm unable to deploy nginx apps to Dokku. The app doesn't start. When I run inside the nginx container, and execute `/start web`, I get:

```
root@5746c037ead8:/# /start web
bash: line 1: /build/app/nginx.conf: No such file or directory
```

Any help would be greatly appreciated. Thank you!

**Comment by ghost** [comment]
Thanks for the report! It should be fixed now, but you will have to manually build buildstep to get the new buildpack.

Instructions (to be run on your dokku server):
- `git clone https://github.com/progrium/buildstep`
- `cd buildstep`
- `sudo make build`

**Comment by amaltson** [comment]
Thank you @rhy-jot! I'll give it a try right now.

**Comment by amaltson** [comment]
Just deployed and it works, thank you!

**Comment by ghost** [comment]
Anytime!
