### ISSUE TITLE
Override www directory with env var

### ISSUE THREAD

**Issue by jgallen23** [progrium/buildpack-nginx#10]
Rather than overriding the entire nginx.conf, it'd be nice to just have an env var that I can set to override www.  Not sure if nginx.conf.erb can have any sort of logic to detect if the env variable is set or not

**Comment by sputnikus** [comment]
Since it's just ERB, simple ENV.fetch('<WWW_ENV>', '/app/www') or something like that should be enough...

**Comment by ghost** [comment]
Feature added in 04ecbabbc47c590308733d99a82c5ccf5346b78a

**Comment by jgallen23** [comment]
thanks!

**Comment by tony2nite** [comment]
Can I please confirm setting the environment variable like this is the way to access this new override, for example:

`ssh dokku@mysite.com config:set [APP_NAME] root=/app/dist`

I'm seemingly getting the variable set up correctly, but not being read by the build-pack plugin.

**Comment by ghost** [comment]
Have you rebuilt buildstep?

``` bash
# On your dokku server, as root:
git clone https://github.com/progrium/buildstep
cd buildstep
make build
```

After you rebuild you'll need to push/rebuild your application

**Comment by tony2nite** [comment]
Great, that works fine. I'd try restarting, updating plugins etc but not a rebuild of buildstep. Thanks again.
