### ISSUE TITLE
Creating a Reverse Proxy Service

### ISSUE THREAD

**Issue by AlJohri** [progrium/buildpack-nginx#6]
I'm interested in using buildpack-nginx to add several `upstream` blocks and add several `location` blocks to create a reverse proxy service for the components of my Service Oriented Architecture.

Is this possible with the `nginx.conf.erb`?

So the end goal is to have the `host` nginx point `\` to my subdomain, `dev`, for example. And my `dev` subdomain can route `\` to a `www-dev` service (another subdomain)

I apologize for asking without testing myself!

@rhy-jot

**Comment by ghost** [comment]
Should work fine
