### ISSUE TITLE
custom-build not picked up during build

### ISSUE THREAD

**Issue by holmesal** [progrium/buildpack-nginx#7]
Hey! Awesome work with this buildpack.

I'm having some trouble getting custom-build to run. I've got a file called `custom-build` in my project root that looks like so:

``` bash
#!/usr/bin/env bash

apt-get install nodejs
apt-get install npm

npm install && bower install && grunt build
```

And I've made that file executable. I'm able to run this file from inside the dokku container, but it's not being run as part of the build. Is there anything I need to do besides just having this file in my project root? I assumed the buildpack would pick it up (like `.nginx`)

Thanks!

**Comment by ghost** [comment]
Apologies for the late reply! I'm able to use `custom-build` successfully on the latest version of the buildpack (executable, in the root directory, committed). Just to make sure - by `project root` you mean the directory where `.git` lives and not in `www`? If so, could you check if you're up to date?
- `docker run -it progrium/buildstep /bin/bash`
- `tail -n 3 /build/buildpacks/buildpack-nginx/bin/compile`

You should see 

``` bash
if [[ -e $1/${CUSTOM_BUILD:-custom-build} ]]; then
    $1/${CUSTOM_BUILD:-custom-build} "$@"
fi
```

If you're missing those lines you can download and import¹ a [buildstep release](https://github.com/progrium/buildstep/releases) or [build the latest buildstep](https://github.com/progrium/buildstep#building-buildstep)

1: `curl -L <url from releases page> | gunzip -cd | docker import - progrium/buildstep`

**Comment by holmesal** [comment]
Ah - turns out I wasn't building buildstep properly - importing the latest release worked like a charm.

Thanks!
